# Set-Up

In [1]:
!pip install allosaurus

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 42.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 kB 11.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for unicodecsv: filename=unicodecsv-0.14.1-py3-none-any.whl size=10745 sha256=12ec1ccebd4483ccaae71fd802527169dc246f5736200d173dcd4f72b681bb61
  Stored in directory: /root/.cache/pip/wheels/9c/ea/66/8e45247b09052a933eb1a680b7c64802298faba58aac9b346b
Successfully built unicodecsv


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:

# SET TO PROJECT FOLDER
dir = '/content/drive/MyDrive/cse256'

# Features DF

In [4]:
import pandas as pd

meta = pd.read_csv('drive/MyDrive/cse256/speakers_all.csv')
display(meta)

age  age_onset              birthplace  filename native_language  \
0     24.0       12.0         koussi, senegal   balanta         balanta   
1     18.0       10.0          buea, cameroon  cameroon        cameroon   
2     48.0        8.0  hong, adamawa, nigeria  fulfulde        fulfulde   
3     42.0       42.0   port-au-prince, haiti   haitian         haitian   
4     40.0       35.0   port-au-prince, haiti   haitian         haitian   
...    ...        ...                     ...       ...             ...   
2167  46.0        5.0          lagos, nigeria   yoruba3          yoruba   
2168  46.0       12.0          lagos, nigeria   yoruba4          yoruba   
2169  47.0        2.0         ibadan, nigeria   yoruba5          yoruba   
2170  31.0        1.0     bethel, alaska, usa    yupik1           yupik   
2171  24.0       14.0      bulawayo, zimbabwe     zulu1            zulu   

         sex  speakerid   country  file_missing?  Unnamed: 9  Unnamed: 10  \
0       male        788   senegal           True         NaN          NaN   
1       male       1953  cameroon           True         NaN          NaN   
2       male       1037   nigeria           True         NaN          NaN   
3       male       1165     haiti           True         NaN          NaN   
4       male       1166     haiti           True         NaN          NaN   
...      ...        ...       ...            ...         ...          ...   
2167  female        766   nigeria          False         NaN          NaN   
2168    male        851   nigeria          False         NaN          NaN   
2169  female       2023   nigeria          False         NaN          NaN   
2170  female        571       usa          False         NaN          NaN   
2171  female        406  zimbabwe          False         NaN          NaN   

     Unnamed: 11  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
2167         NaN  
2168         NaN  
2169         NaN  
2170         NaN  
2171         NaN  

[2172 rows x 12 columns]

# Load in Speaker-to-Phonemes dictionary

In [32]:
import pickle

speaker_to_phonemes = pickle.load(open(dir + '/Phonemes/speakers_to_phonemes_dict.pickle', 'rb'))

# Get list of unique IPA phoneme vocab

In [33]:
all_phonemes = [item for sublist in speaker_to_phonemes.values() for item in sublist]
unique_phonemes = list(set(all_phonemes))

phone_code = {}
num = 1
for phon in unique_phonemes:
  phone_code[phon] = num
  num += 1

phone_code

{'e': 1,
 'ʝ': 2,
 'ә': 3,
 'ɾ': 4,
 'ʏ': 5,
 'ʂ': 6,
 'ː': 7,
 '̪': 8,
 'ɛ': 9,
 'ʋ': 10,
 'ə': 11,
 'ɨ': 12,
 'ð': 13,
 'l': 14,
 'd': 15,
 'k': 16,
 'i': 17,
 '̟': 18,
 'ɴ': 19,
 '͡': 20,
 'm': 21,
 'f': 22,
 'w': 23,
 'x': 24,
 'ɒ': 25,
 'ʌ': 26,
 'o': 27,
 '̥': 28,
 'h': 29,
 'ɰ': 30,
 't': 31,
 '̤': 32,
 'ʔ': 33,
 'y': 34,
 'r': 35,
 'θ': 36,
 'β': 37,
 ' ': 38,
 'v': 39,
 'ç': 40,
 'g': 41,
 'ɻ': 42,
 'ʲ': 43,
 'ʁ': 44,
 'ø': 45,
 'u': 46,
 'ɡ': 47,
 'ɪ': 48,
 'ɣ': 49,
 '̞': 50,
 '̆': 51,
 'ɟ': 52,
 'b': 53,
 'z': 54,
 'ɤ': 55,
 'ʰ': 56,
 'ʐ': 57,
 'œ': 58,
 's': 59,
 'ŋ': 60,
 'a': 61,
 'n': 62,
 'æ': 63,
 'ɕ': 64,
 'ɹ': 65,
 'ʊ': 66,
 'j': 67,
 'ɯ': 68,
 'ɳ': 69,
 'ʃ': 70,
 '̩': 71,
 'ɲ': 72,
 'ɑ': 73,
 'ʀ': 74,
 'ɔ': 75,
 'ʒ': 76,
 '̚': 77,
 'ɥ': 78,
 '̃': 79,
 'p': 80}

# Convert phonemes into BoW feature vector

In [70]:
import glob, pickle

lang_list = ['english', 'spanish', 'arabic', 'mandarin', 'french', 'korean']

speakers_to_bow = {}
speaker_labels = {}

for lang in lang_list:
  for speaker in speaker_to_phonemes.keys():
  # for lang in lang_list:
    if lang in speaker:
      phonemes = speaker_to_phonemes[speaker]

      phone_bow = []
      for phon in phone_code.keys():
        count = phonemes.count(phon)
        phone_bow.append(count)

      speakers_to_bow[speaker] = phone_bow
      speaker_labels[speaker] = lang

In [71]:
from sklearn.decomposition import PCA

values = list(speakers_to_bow.values())
names = list(speakers_to_bow.keys())
langs = [speaker_labels[n] for n in names]
print(langs)

lengs = {}
for lang in lang_list:

  if lang not in lengs:
    lengs[lang] = 0

  for name in names:
    if lang in name:
      # print('yes')
      lengs[lang] = lengs[lang] + 1

print(lengs)
pca = PCA(n_components=3)
components = pca.fit_transform(values)
print(pca.explained_variance_ratio_)

['english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english', 'english'

In [72]:
import plotly.express as px

fig = px.scatter_3d(components, x=0, y=1, z=2, color=langs)
fig.show()

In [73]:
# fig = px.scatter_matrix(
#     components,
#     labels=langs,
#     dimensions=range(3),
#     color=langs
# )
# fig.update_traces(diagonal_visible=False)
# fig.show()

In [74]:
import numpy as np

# lang_to_centroid = {}
# lang_to_std = {}
# for lang in lang_to_comps:
#   centroid = np.average(np.asarray(lang_to_comps[lang]), axis=0)
#   lang_to_centroid[lang] = centroid
#   lang_to_std[lang] = np.std(np.asarray(lang_to_comps[lang]))


# for lang in lang_to_comps:
#   print('PCA Distance from English centroid to', lang, 'is: ', np.linalg.norm(lang_to_centroid['english'] - lang_to_centroid[lang]))
#   print('PCA Standard Deviation of ', lang, 'is: ', lang_to_std[lang])

lang_points = {}
for lang in lang_list:
  if lang not in lang_points:
    lang_points[lang] = []
for lang in lang_list:
  for i in range(components.shape[0]):
    # print(names[i])
    if lang in names[i]:
      # print(names[i])
      lang_points[lang].append(components[i])

pca_centroid = {}
pca_std = {}
for lang in lang_list:
  centroid = np.average(np.asarray(lang_points[lang]), axis=0)
  pca_centroid[lang] = centroid
  pca_std[lang] = np.std(np.asarray(lang_points[lang]))

lang_dists = np.zeros((len(lang_list), len(lang_list)))
for i in range(len(lang_list)):
  for j in range(len(lang_list)):
    lang_dists[i][j] = np.linalg.norm(pca_centroid[lang_list[i]] - pca_centroid[lang_list[j]])

print(lang_list)
print(lang_dists)
for lang in lang_list:
#   # print('T-sne Distance from English centroid to', lang, 'is: ', np.linalg.norm(tsne_centroid['english'] - tsne_centroid[lang]))
  print('PCA Standard Deviation of ', lang, 'is: ', pca_std[lang])

# mandarin_italian_dist = np.linalg.norm(lang_to_centroid['italian'] - lang_to_centroid['mandarin'])
# print("Mandarin-Italian Centroid Distance: ", mandarin_italian_dist)

['english', 'spanish', 'arabic', 'mandarin', 'french', 'korean']
[[ 0.          5.97655629 10.92309587  5.31213356  3.81997638  7.13200091]
 [ 5.97655629  0.          6.76024753  1.5351631   4.91909325  1.21832685]
 [10.92309587  6.76024753  0.          6.32020802 11.45523985  6.4743793 ]
 [ 5.31213356  1.5351631   6.32020802  0.          5.18885916  2.36401041]
 [ 3.81997638  4.91909325 11.45523985  5.18885916  0.          5.75380288]
 [ 7.13200091  1.21832685  6.4743793   2.36401041  5.75380288  0.        ]]
PCA Standard Deviation of  english is:  4.68708625707327
PCA Standard Deviation of  spanish is:  7.649946317188948
PCA Standard Deviation of  arabic is:  16.30652013546133
PCA Standard Deviation of  mandarin is:  10.356768440961005
PCA Standard Deviation of  french is:  6.5929580091031434
PCA Standard Deviation of  korean is:  6.696572282797088


# T-SNE

In [75]:
from sklearn.manifold import TSNE
# print(values.shape)

data = np.array(values)
tsne_embedding = TSNE(n_components = 3, perplexity=40, learning_rate = 'auto', n_iter = 5000).fit_transform(data)
# proj2 = TSNE(n_components = 3, perplexity=20, learning_rate = 'auto', n_iter = 3000).fit_transform(data)



In [76]:
import plotly.express as px

fig1 = px.scatter_3d(tsne_embedding, x=0, y=1, z=2, color=langs)
fig1.show()

# fig2 = px.scatter_3d(proj2, x=0, y=1, z=2, color=langs)
# fig2.show()

In [77]:
from sklearn.metrics import r2_score
from sklearn.cross_decomposition import PLSRegression

print(proj1.shape)
# print(len(names))
# print(len(values))

lang_to_comps = {}
for lang in lang_list:

  if lang not in lang_to_comps:
    lang_to_comps[lang] = []

  for name, comp in zip(names, values):
    if lang in name:
      lang_to_comps[lang].append(comp)

lang_points = {}
for lang in lang_list:
  if lang not in lang_points:
    lang_points[lang] = []
for lang in lang_list:
  for i in range(tsne_embedding.shape[0]):
    # print(names[i])
    if lang in names[i]:
      # print(names[i])
      lang_points[lang].append(tsne_embedding[i])

# print(lang_points)

tsne_centroid = {}
tsne_std = {}
for lang in lang_list:
  centroid = np.average(np.asarray(lang_points[lang]), axis=0)
  tsne_centroid[lang] = centroid
  tsne_std[lang] = np.std(np.asarray(lang_points[lang]))

lang_dists = np.zeros((len(lang_list), len(lang_list)))
for i in range(len(lang_list)):
  for j in range(len(lang_list)):
    lang_dists[i][j] = np.linalg.norm(tsne_centroid[lang_list[i]] - tsne_centroid[lang_list[j]])

print(lang_list)
print(lang_dists)

for lang in lang_to_comps:
  # print('T-sne Distance from English centroid to', lang, 'is: ', np.linalg.norm(tsne_centroid['english'] - tsne_centroid[lang]))
  print('T-sne Standard Deviation of ', lang, 'is: ', tsne_std[lang])


total_vars = []
for i in range(1, 4):
        tsne_matrix_current = pd.DataFrame(tsne_embedding[:, 0:i])
        pls_current = PLSRegression(n_components = i)
        pls_current.fit(tsne_matrix_current, data)
        y_pred_current = pls_current.predict(tsne_matrix_current)
        total_vars.append(r2_score(data, y_pred_current, \
        multioutput = 'variance_weighted'))

print(total_vars[0], total_vars[1] - total_vars[0], total_vars[2] - total_vars[0])

(1023, 3)
['english', 'spanish', 'arabic', 'mandarin', 'french', 'korean']
[[ 0.         14.33471966 18.47164726 11.69999504 12.11837101 15.91401291]
 [14.33471966  0.         11.14172649  6.16618681 12.50361347  3.76632643]
 [18.47164726 11.14172649  0.         13.27210331 22.55123901 12.47071362]
 [11.69999504  6.16618681 13.27210331  0.         10.97676182  9.70729542]
 [12.11837101 12.50361347 22.55123901 10.97676182  0.         13.33183956]
 [15.91401291  3.76632643 12.47071362  9.70729542 13.33183956  0.        ]]
T-sne Standard Deviation of  english is:  13.475258
T-sne Standard Deviation of  spanish is:  16.745226
T-sne Standard Deviation of  arabic is:  17.90273
T-sne Standard Deviation of  mandarin is:  18.067152
T-sne Standard Deviation of  french is:  16.282356
T-sne Standard Deviation of  korean is:  15.661675
0.34965621818934883 0.013983826162341062 0.04542130153138518


# UMAP

In [78]:
pip install umap-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [79]:
import umap.umap_ as umap

In [80]:
umap_embedding = umap.UMAP(n_neighbors = 20, n_components=3, min_dist = 0.01, metric = 'euclidean').fit_transform(data)
proj2 = umap.UMAP(n_neighbors = 30, n_components=3, min_dist = 0.01, metric = 'correlation').fit_transform(data)
# print(data.shape)
# print(len(langs))
fig1 = px.scatter_3d(
    umap_embedding, x=0, y=1, z=2,
    color=langs
)
fig1.update_traces(marker_size=8)
fig1.show()

# fig2 = px.scatter_3d(
#     proj2, x=0, y=1, z=2,
#     color=langs
# )
# fig2.update_traces(marker_size=8)
# fig2.show()

In [81]:



lang_points = {}
for lang in lang_list:
  if lang not in lang_points:
    lang_points[lang] = []
for lang in lang_list:
  for i in range(umap_embedding.shape[0]):
    # print(names[i])
    if lang in names[i]:
      # print(names[i])
      lang_points[lang].append(umap_embedding[i])

# print(lang_points)

umap_centroid = {}
umap_std = {}
for lang in lang_list:
  centroid = np.average(np.asarray(lang_points[lang]), axis=0)
  umap_centroid[lang] = centroid
  umap_std[lang] = np.std(np.asarray(lang_points[lang]))


lang_dists = np.zeros((len(lang_list), len(lang_list)))
for i in range(len(lang_list)):
  for j in range(len(lang_list)):
    lang_dists[i][j] = np.linalg.norm(umap_centroid[lang_list[i]] - umap_centroid[lang_list[j]])

print(lang_list)
print(lang_dists)
print(umap_std)
for lang in lang_to_comps:
  # print('UMAP Distance from English centroid to', lang, 'is: ', np.linalg.norm(tsne_centroid['english'] - tsne_centroid[lang]))
  print('UMAP Standard Deviation of ', lang, 'is: ', umap_std[lang])

total_vars = []
for i in range(1, 4):
        UMAP_matrix_current = pd.DataFrame(umap_embedding[:, 0:i])
        pls_current = PLSRegression(n_components = i)
        pls_current.fit(UMAP_matrix_current, data)
        y_pred_current = pls_current.predict(UMAP_matrix_current)
        total_vars.append(r2_score(data, y_pred_current, \
        multioutput = 'variance_weighted'))

print(total_vars[0], total_vars[1] - total_vars[0], total_vars[2] - total_vars[0])



['english', 'spanish', 'arabic', 'mandarin', 'french', 'korean']
[[0.         1.18721557 1.88847315 1.03067982 0.87578112 1.19753706]
 [1.18721557 0.         0.89025187 0.21655129 1.21884906 0.12385552]
 [1.88847315 0.89025187 0.         1.04925108 2.10213423 0.98439527]
 [1.03067982 0.21655129 1.04925108 0.         1.0574795  0.23787163]
 [0.87578112 1.21884906 2.10213423 1.0574795  0.         1.14648664]
 [1.19753706 0.12385552 0.98439527 0.23787163 1.14648664 0.        ]]
{'english': 8.141246, 'spanish': 8.387926, 'arabic': 8.769027, 'mandarin': 8.397606, 'french': 7.957212, 'korean': 8.325585}
UMAP Standard Deviation of  english is:  8.141246
UMAP Standard Deviation of  spanish is:  8.387926
UMAP Standard Deviation of  arabic is:  8.769027
UMAP Standard Deviation of  mandarin is:  8.397606
UMAP Standard Deviation of  french is:  7.957212
UMAP Standard Deviation of  korean is:  8.325585
0.33084241253336755 0.03916852374072821 0.06334797355253113


# Top N Languages

In [26]:
lang_list = [?g_list:
    # if lang in speaker:
    #   phonemes = speaker_to_phonemes[speaker]

    #   phone_bow = []
    #   for phon in phone_code.keys():
    #     count = phonemes.count(phon)
    #     phone_bow.append(count)

    #   speakers_to_bow[speaker] = phone_bow
    #   speaker_labels[speaker] = lang

In [27]:
# values = list(speakers_to_bow.values())
# names = list(speakers_to_bow.keys())
# langs = [speaker_labels[n] for n in names]

# pca = PCA(n_components=3)
# components = pca.fit_transform(values)

In [ ]:
# fig = px.scatter_3d(components, x=0, y=1, z=2, color=langs)
# fig.show()

In [ ]:
# lang_to_comps = {}
# for lang in lang_list:

#   if lang not in lang_to_comps:
#     lang_to_comps[lang] = []

#   for name, comp in zip(names, values):
#     if lang in name:
#       lang_to_comps[lang].append(comp)


# lang_to_centroid = {}
# for lang in lang_to_comps:
#   centroid = np.average(np.asarray(lang_to_comps[lang]), axis=0)
#   lang_to_centroid[lang] = centroid


# english_centroid = lang_to_centroid['english']
# for lang in lang_to_centroid:
#   if lang!='english':
#     distance = np.linalg.norm(lang_to_centroid[lang] - english_centroid)
#     print(lang.upper(), ' distance: ', distance)

SPANISH  distance:  6.355981390154438
MANDARIN  distance:  6.446347753645995
FRENCH  distance:  4.601127272496815
KOREAN  distance:  7.867154141731113
PORTUGUESE  distance:  3.273000741863762
RUSSIAN  distance:  6.196142056091757
DUTCH  distance:  4.834054044140781
TURKISH  distance:  10.220450266216522
